name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.0.0
          cache: 'npm' # Use 'npm' temporarily; we will add pnpm caching manually.

      - name: Install pnpm manually
        run: npm install -g pnpm@latest

      # Cache pnpm store directory
      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Debug pnpm
        run: |
          pnpm --version
          which pnpm
          echo "PATH: $PATH"

      - name: Build Frontend
        run: pnpm --filter frontend build

      - name: Build Backend
        run: pnpm --filter backend build
